# Generated by Django 4.2.5 on 2023-10-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_imagepost_image_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='image_picture',
            field=models.ImageField(null=True, upload_to='image_posts/'),
        ),
    ]
