# Generated by Django 3.2.20 on 2023-09-03 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
