# Generated by Django 4.2.5 on 2023-10-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_imagepost_tags_comment_imagepost_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='image_picture',
            field=models.TextField(blank=True, db_column='data', null=True),
        ),
    ]
