# Generated by Django 4.2.5 on 2023-10-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_imagepost_image_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='userAuth',
            field=models.TextField(blank=True, null=True),
        ),
    ]
