# Generated by Django 4.2.5 on 2023-10-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profilepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepage',
            name='exp_container',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
