# Generated by Django 4.2.5 on 2023-11-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_comment_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='profile',
        ),
        migrations.AddField(
            model_name='comment',
            name='profileName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
