# Generated by Django 4.2.5 on 2023-10-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_profilepage_user_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepage',
            name='displayName',
            field=models.TextField(blank=True, null=True),
        ),
    ]
