# Generated by Django 4.2.5 on 2023-10-19 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_imagepost_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.profilepage'),
        ),
    ]
