# Generated by Django 4.2.5 on 2023-10-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_comment_imagepost_comment_post_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepost',
            name='image',
        ),
        migrations.AddField(
            model_name='imagepost',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
