# Generated by Django 4.2.5 on 2023-10-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_imagepost_image_imagepost_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
